output_dir = '/workspace/diffusion-pipe/output'
dataset = '/workspace/diffusion-pipe/examples/dataset.toml'
epochs = 1000
micro_batch_size_per_gpu = 1
pipeline_stages = 1
gradient_accumulation_steps = 1
gradient_clipping = 1.0
warmup_steps = 100
eval_every_n_epochs = 1
eval_before_first_step = true
eval_micro_batch_size_per_gpu = 1
eval_gradient_accumulation_steps = 1
save_every_n_epochs = 10
checkpoint_every_n_minutes = 120
activation_checkpointing = true
partition_method = 'parameters'
save_dtype = 'bfloat16'
caching_batch_size = 1
steps_per_print = 1
video_clip_mode = 'single_beginning'


[model]
type = 'wan'
ckpt_path = '/workspace/diffusion-pipe/checkpoints/Wan2.1-T2V-14B'
dtype = 'bfloat16'
timestep_sample_method = 'logit_normal'


[adapter]
type = 'lora'
rank = 32
dtype = 'bfloat16'


[optimizer]
type = 'adamw_optimi'
lr = 2e-5
betas = [0.9, 0.99]
weight_decay = 0.01
eps = 1e-8
